<?php

namespace App\Filament\Resources\UserResource\Pages;

use App\Filament\Resources\UserResource;
use App\Models\User;
use AymanAlhattami\FilamentPageWithSidebar\Traits\HasPageSidebar;
use Filament\Resources\Pages\EditRecord;
use Filament\Resources\Pages\Page;
use Illuminate\Database\Eloquent\Model;

class ChangePassword extends EditRecord
{
    use HasPageSidebar;
    protected static string $resource = UserResource::class;

    public Model | int | string | null $record;

//    public User $record;

    public $current_password;
    public $new_password;
    public $new_password_confirmation;

    public function mount($record = null): void
    {
        $this->record = auth()->user()->id;

        parent::mount($this->record); // TODO: Change the autogenerated stub
    }

    protected static string $view = 'filament.resources.user-resource.pages.change-password';


}
