<?php

namespace App\Filament\Resources\UserResource\Pages;

use App\Filament\Resources\UserResource;
use AymanAlhattami\FilamentPageWithSidebar\Traits\HasPageSidebar;
use Filament\Actions;
use Filament\Forms\Components\TextInput;
use Filament\Resources\Pages\EditRecord;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Model;

class UserProfile extends EditRecord
{
    use HasPageSidebar;
    protected static string $resource = UserResource::class;

    public Model | int | string | null $record;

    public function mount($record = null): void
    {
        $this->record = auth()->user()->id;
        parent::mount($this->record); // TODO: Change the autogenerated stub
    }

    protected function getFormSchema(): array
    {
        return [
          TextInput::make('name')
          ->label('Name')
          ->placeholder('Enter Your Name')
          ->required(),

          TextInput::make('email')
          ->label('Email')
          ->placeholder('Enter Your Email')
          ->email(),
        ];
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        return $data;
    }
}
